# needs: [tests]  # require tests to pass before deploy runs

name: Build and Push

# on:
#   push:
#     # Pattern matched against refs/tags
#     tags:
#       - '**' # Push events to every tag including hierarchical tags like v1.0/beta

on:
  push:
    branches:
      - master

# maybe trigger build/push on release tags?
# but this also works for my use case
jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: ["1.21.5"]
    #     golangci-version: ["v1.51.2"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Go Tests
      uses: ./.github/actions/tests
  docker-build:
    runs-on: ubuntu-latest
    needs: test
    environment: 'Dockerhub'
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Docker Build
      uses: ./.github/actions/docker
      with:
        latest: false
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    