name: Test Builds

on:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    # not working for some reason
    # strategy:
    #   matrix:
    #     go-version: ["1.21.5"]
    #     golangci-version: ["v1.51.2"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Go Tests
      uses: ./.github/actions/tests
  ## Build and test code to ensure it will work in a container
  ## Would be nice to do this on every PR, but it takes too long and uses too many resources
  # build_test:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   environment: 'Dockerhub'
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Run Docker Build Test
  #     uses: ./.github/actions/docker
  #     with:
  #       latest: false
  #       push: false
  #       dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}