name: Test Builds

on:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    # not working for some reason
    # strategy:
    #   matrix:
    #     go-version: ["1.21.5"]
    #     golangci-version: ["v1.51.2"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Go Tests
      uses: ./.github/actions/tests
      # with:
      #   go_version: '${{ matrix.go-version }}'
      #   golangci_version: '${{ matrix.golangci-version }}'
  # Build and test code to ensure it will work in a container
  build_test:
    needs: test
    runs-on: ubuntu-latest
    environment: 'Dockerhub' 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Docker Build Test
      uses: ./.github/actions/docker
      with:
        latest: false
        push: false