---
name: Create Official Release and Push Artifacts

on:
  push:
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: ["1.21.5"]
    #     golangci-version: ["v1.51.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tests
        uses: ./.github/actions/tests
  create_release:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
  # build and push docker image
  release-docker:
    runs-on: ubuntu-latest
    needs:
      - tests
      - create_release
    environment: 'Dockerhub'
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Docker Build
        uses: ./.github/actions/docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
  # 
  # adds binaries to release
  # https://github.com/goreleaser/goreleaser-action
  release-go:
    runs-on: ubuntu-latest
    needs:
      - tests
      - create_release
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: ./.github/actions/go
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"